version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: roleta-inteli-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-sistema_fila}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-rootpassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - roleta-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roleta-inteli-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-rootpassword}
      - DB_NAME=${DB_NAME:-sistema_fila}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - WEBHOOK_URL=${WEBHOOK_URL:-https://webhook.site/your-unique-url}
    depends_on:
      - mysql
    networks:
      - roleta-network

volumes:
  mysql_data:

networks:
  roleta-network:
    driver: bridge
